In [32]:
import lumicks.pylake as lk
import matplotlib.pyplot as plt
import numpy as np
d = lk.File("Data/TrmD_marker24.h5")

In [33]:
channel = d.downsampled_force2
%matplotlib widget
zoomer = channel.range_selector

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [34]:
zoomer.ranges

array([[1606227196588595800, 1606227263080218200],
       [1606227324932890200, 1606227355859226200]])

In [35]:
class fholder:
    def __init__(self,f):
        self.f = f

In [36]:
%matplotlib widget
channel = zoomer.slices[0]
print(zoomer.slices[0])
slicedict = {f'zoom{i}': fholder(d.downsampled_force2[slice(*zoomer.ranges[i])]) for i in range(len(zoomer.ranges))}
selector = lk.FdRangeSelector(slicedict)
plt.show()
#for channel in selector.slices:
 #   plt.figure()
 #   channel.plot()


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

interactive(children=(Dropdown(description='curve', options=('zoom0', 'zoom1'), value='zoom0'), Output()), _do…

In [37]:
selector.ranges

{'zoom0': array([], dtype=float64),
 'zoom1': array([[1606227339070643800, 1606227343599143000],
        [1606227344703655000, 1606227348790349400],
        [1606227349894861400, 1606227354312909400]])}

In [38]:
flat_ranges = []
for array in [selector.ranges[key] for key in selector.ranges]:
    for item in array:
        flat_ranges.append(item)
flat_ranges

[array([1606227339070643800, 1606227343599143000]),
 array([1606227344703655000, 1606227348790349400]),
 array([1606227349894861400, 1606227354312909400])]

In [52]:
fdc = lk.fdcurve.FDCurve(d, flat_ranges[0][0], flat_ranges[0][1], 'test', force = 2, distance = 1)
print(fdc.d.data)
d.fdcurves['test'] = fdc
plt.figure()
plt.plot(fdc.d.data, fdc.f.data)
plt.show()

[0.08595468 0.08931438 0.10032504 0.14572128 0.17928564 0.20350278
 0.22094294 0.23441026 0.24599782 0.25629955 0.25792856 0.2672371
 0.27168226 0.27963577 0.28758285 0.28889547 0.29127793 0.29478793
 0.29369526 0.29135934 0.29314681 0.29274247 0.29500251 0.29556285
 0.29650821 0.29483476 0.30353676 0.30143361 0.29740656 0.29407396
 0.28994119 0.28410726 0.27747598 0.27216664 0.26129722 0.24469721
 0.23292681 0.21650846 0.19364935 0.16074161 0.12524191]


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [50]:
smoothed_forces = []
interp_distances = []
kernel_size = 1
target = 5000
for sel_range in flat_ranges:
    slc = slice(*sel_range)
    forces = d.force1x[slc].data
    step = int(len(forces) / target)
    timestamps = d.force1x[slc].timestamps
    kernel = np.ones(kernel_size) / kernel_size
    smoothed_forces.append(np.convolve(forces, kernel, mode='same'))
    interp_distances.append(np.interp(timestamps, d.downsampled_force1[slc].timestamps,
                                     d.distance1[slc].data))


In [51]:
step = 70
plt.figure()
plt.plot(interp_distances[0][::step])
plt.figure()
plt.plot(smoothed_forces[0][::step])
print(len(interp_distances[0][::step]), len(smoothed_forces[0][::step]))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

5055 5055


In [ ]:
hfile = lk.File('test.h5','w')
for 
hfile.create_dataset('curve_1', data=)

In [ ]:
print(d)